### ISSUE TITLE
octTree throw segmentation fault when batch deletion enabled

### ISSUE THREAD

**Issue by RomaLzhih** [cmuparlay/pbbsbench#17]
Hi developers,

I am currently running the `benchmark\nearestNeighbors\octTree`. After uncommenting the `batch_deletion` in the [driver file](https://github.com/cmuparlay/pbbsbench/blob/master/benchmarks/nearestNeighbors/octTree/neighbors.h#L70C1-L70C53). It throws a segmentation fault within the [recursive deletion function](https://github.com/cmuparlay/pbbsbench/blob/master/benchmarks/nearestNeighbors/octTree/k_nearest_neighbors.h#L423), i.e.,
```
$ ./neighbors -d 3 -k 100 test.in 
ANN: build tree: 0.1763
Segmentation fault (core dumped)
```

The inputs are generated using the default point generator provided, i.e., `./randPoints`.

I am using g++ 12.2.1 as a compiler on Linux.

Reproduce procedure:
```
// uncomment the function above
cd testData/geometryData/
make clean; make
./randPoints -s -d 3 10000000 test.in
cp test.in ../../benchmarks/nearestNeighbors/octTree
cd ../../benchmarks/nearestNeighbors/octTree
make clean; make
./neighbors -d 3 -k 100 test.in 
```

Any suggestions would be helpful. Thanks!

**Comment by gblelloch** [comment]
Thanks for pointing out the issue.   I'm ccing this to Magdalen Dobson, who
knows more about the batch operations.   It could be that some other
settings need to be changed if uncommenting the batch_deletion code.

Guy

**Comment by gblelloch** [comment]
BTW, going back to branch d219d0242c0167f4c7a90ab669e2c2681c797fe4 seems to
make the code work.

Guy

**Comment by RomaLzhih** [comment]
Thanks for your reply! Unfortunately, it still does not work on my machine. Some other settings may be needed. :(

> BTW, going back to branch [d219d02](https://github.com/cmuparlay/pbbsbench/commit/d219d0242c0167f4c7a90ab669e2c2681c797fe4) seems to make the code work. Guy

**Comment by gblelloch** [comment]
Thanks for bringing this up. I have been looking into the issue and I found
the bug that was causing the segfault. With the latest commit, you should
be able to reproduce the results on batch insertion and deletion from the
paper.

However, I did also find some other small bugs that affected the structure
of the tree when it was built using the batch insert/delete functions.
Those will take me a little longer to track down and fix. I will email
again once those are complete.

Thanks again for your interest in our work and please let me know if you
find any other issues!

Best,
Magdalen

**Comment by RomaLzhih** [comment]
> 

Thanks for your feedback! The raw code can run smoothly now. 

However, as you mentioned, there are still bugs that remain. For example, if one changes the points `v2` in [batch-deletion](https://github.com/cmuparlay/pbbsbench/blob/master/benchmarks/nearestNeighbors/octTree/neighbors.h#L71) as `v` (i.e., delete all points in the tree), the program will throw `ERROR: deleting the root or one of its two children is not supported`. Swapping the order of [batch-insertion](https://github.com/cmuparlay/pbbsbench/blob/master/benchmarks/nearestNeighbors/octTree/neighbors.h#L75) and  [batch-deletion](https://github.com/cmuparlay/pbbsbench/blob/master/benchmarks/nearestNeighbors/octTree/neighbors.h#L71) will incur the same problem as well. 

Thanks again :)

Best, 
Ziyang
