### ISSUE TITLE
Duplication of documentation

### ISSUE THREAD

**Issue by athas** [cmuparlay/pbbsbench#18]
The benchmarks seem to be documented in both the [docs](https://github.com/cmuparlay/pbbsbench/tree/master/docs) folder and the [benchmarks](https://github.com/cmuparlay/pbbsbench/tree/master/benchmarks) top level folders.   The latter seem to be wrong or outdated (e.g. the description of the Kuzmin dataset for convexHull is wrong), and not what is shown on the web page.  I suggest deleting the misleading documentation in the benchmarks directory.

**Comment by gblelloch** [comment]
Thanks for pointing this out.   Indeed the ones in the benchmark folders
are outdated (from PBBS version 1).   We will remove them when we have a
chance.

Guy

**Comment by gblelloch** [comment]
Fixed.   I removed the old incorrect documentation.
