### ISSUE TITLE
randomSeq does not behave in accordance with its specification

### ISSUE THREAD

**Issue by athas** [cmuparlay/pbbsbench#19]
The specification for randomSeq states:

```html
The double precision version generates reals uniformly
at random in the range <tt>[0,1)</tt> (within the precision).
```

Yet here are the results from asking it to generate 10 floats:

```
sequenceDouble
8.88211556550e+18
1.37386030260e+19
5.25446871372e+18
8.38175348343e+18
8.58707257471e+17
1.63527231515e+19
1.03287215791e+19
3.74506799124e+18
8.68449035431e+18
5.30940887660e+17
```

These numbers are clearly outside the `[0,1)` range.

**Comment by gblelloch** [comment]
Thanks for pointing this out.    We will update either the generator or the
documentation when we have a chance.

Guy

**Comment by gblelloch** [comment]
Fixed.   Now generates from 0 to 1.
