### ISSUE TITLE
There are conflict markers in some files

### ISSUE THREAD

**Issue by gilbertmike** [cmuparlay/pbbsbench#2]
Not sure if it's accidental or on purpose, but there are conflict markers in these files:

- [nearestNeighbors/octTree/neighbors.h](https://github.com/cmuparlay/pbbsbench/blob/master/comparisonSort/sampleSort/sort.h)
- [comparisonSort/sampleSort/sort.h](https://github.com/cmuparlay/pbbsbench/blob/master/nearestNeighbors/octTree/neighbors.h)
- [common/seqDefs](https://github.com/cmuparlay/pbbsbench/blob/master/common/seqDefs)

**Comment by gblelloch** [comment]
closing old issues.   no longer seems to be the case.
