### ISSUE TITLE
link failed when using openmp

### ISSUE THREAD

**Issue by TheRainstorm** [cmuparlay/pbbsbench#9]
## Enviroment
Ubuntu 22.04
CPU: Ryzen 5800X
GCC: g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0

## Problem
The code is compliled with `PBBFLAGS = -DHOMEGROWN -pthread` in my machine with no specific. I want to use openmp, so I define OPENMP variable when building. (see  `comm/parallelDefs`). However, link failed after using openmp. 

The make output:
```bash
➜  parallelKruskal git:(master) ✗ make OPENMP="y"
g++ -DPARLAY_OPENMP -fopenmp -mcx16 -O3 -std=c++17 -DNDEBUG -I .  -o MSTTime.o -c ../bench/MSTTime.C
g++ -DPARLAY_OPENMP -fopenmp -mcx16 -O3 -std=c++17 -DNDEBUG -I .  -c MST.C -o MST.o
g++ -o MST MSTTime.o MST.o -DPARLAY_OPENMP -fopenmp -ldl
/usr/bin/ld: MST.o:(.bss+0x0): multiple definition of `parlay::in_par_do'; MSTTime.o:(.bss+0xa1): first defined here
collect2: error: ld returned 1 exit status
```

I try `minSpanningForest/parallelKruska` and `breadthFirstSearch/deterministicBFS`, both build failed. It seems this is a common problem.

**Comment by gblelloch** [comment]
This is probably since pbbsbench had not been updated to the latest
parlaylib.   We just updated it now.

You should be able to get the new version by doing a:
  git pull
  git submodule update

There were some bugs with omp in the earlier version.

Guy

**Comment by TheRainstorm** [comment]
Thank you for you timely help, the problem is solved!🥳
